[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "aceso"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic",
    "pydantic-settings",
    "psycopg[binary,pool]",
    "supabase",
    "faster-whisper",
    "pytesseract",
    "pdf2image",
    "pillow",
    "pytest",
    "python-multipart"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
